name: workflow Run
on:
     workflow_run:
         workflows: [Repository Events]
         types: [completed]
jobs:
    echo-string:
        runs-on: ubunto-latest
        steps:
            - run: echo "I was triggered after Repository Events"       